Reprise globale du package

diff --git a/scripts/backup b/scripts/backup
--- a/scripts/backup
+++ b/scripts/backup
@@ -1,33 +1,69 @@
 #!/bin/bash
 
-# Source app helpers
+#=================================================
+# GENERIC STARTING
+#=================================================
+# MANAGE FAILURE OF THE SCRIPT
+#=================================================
+
+# Exit on command errors and treat unset variables as an error
+set -eu
+
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
+
+if [ ! -e .fonctions ]; then
+	# Rapatrie le fichier de fonctions si il n'est pas dans le dossier courant
+	sudo cp ../settings/scripts/.fonctions ./.fonctions
+	sudo chmod a+rx .fonctions
+fi
+source .fonctions
 source /usr/share/yunohost/helpers
 
-# Récupère les infos de l'application.
+#=================================================
+# LOAD SETTINGS
+#=================================================
+
 app=$YNH_APP_INSTANCE_NAME
+
 final_path=$(ynh_app_setting_get $app final_path)
 domain=$(ynh_app_setting_get $app domain)
+db_name=$(ynh_app_setting_get $app db_name)
 
+#=================================================
+# STANDARD BACKUP STEPS
+#=================================================
+# BACKUP OF THE MAIN DIR OF THE APP
+#=================================================
 
-# The parameter $1 is the backup directory location
-# which will be compressed afterward
-backup_dir=$1/apps/$app
-sudo mkdir -p "$backup_dir"
+CHECK_SIZE "$final_path"
+ynh_backup "$final_path" "sources"
 
-# Backup sources & data
-sudo cp -a $final_path/. $backup_dir/sources
+#=================================================
+# BACKUP OF THE NGINX CONFIGURATION
+#=================================================
 
-# Copy Nginx and YunoHost parameters
-sudo cp -a /etc/yunohost/apps/$app/. $backup_dir/yunohost
-sudo cp -a /etc/nginx/conf.d/$domain.d/$app.conf $backup_dir/nginx.conf
+ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf" "nginx.conf"
 
-# Backup db
-root_pwd=$(sudo cat /etc/yunohost/mysql)
-sudo mysqldump -u root -p$root_pwd --no-create-db $app --result-file="$backup_dir/db.sql"
+#=================================================
+# BACKUP OF THE SQL BDD
+#=================================================
 
+ynh_mysql_dump_db "$db_name" > dump.sql
+CHECK_SIZE "dump.sql"
+ynh_backup "dump.sql" "db.sql"
 
-# Copie la configuration de logrotate
-sudo cp -a /etc/logrotate.d/$app $backup_dir/logrotate
+#=================================================
+# SPECIFIC BACKUP
+#=================================================
+# BACKUP LOGROTATE
+#=================================================
 
-# Copie des fichiers du script systemd
-sudo cp -a /etc/systemd/system/$app.service $backup_dir/
+ynh_backup "/etc/logrotate.d/$app" "logrotate"
+
+#=================================================
+# BACKUP SYSTEMD
+#=================================================
+
+ynh_backup "/etc/systemd/system/$app.service" "systemd"
diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,87 +1,131 @@
 #!/bin/bash
 
-source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script
+#=================================================
+# GENERIC STARTING
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
 
-CLEAN_SETUP () {
+source .fonctions
+source /usr/share/yunohost/helpers
+
+#=================================================
+# MANAGE FAILURE OF THE SCRIPT
+#=================================================
+
+ynh_clean_setup () {
 # Nettoyage des résidus d'installation non pris en charge par le script remove.
 	if test -n "$PID_TAIL"
 	then
-		kill -s 15 $PID_TAIL > /dev/null	# Arrête l'exécution de tail.
+		SUPPRESS_WARNING kill -s 15 $PID_TAIL	# Arrête l'exécution de tail.
 		sudo rm -f "$tempfile"
 	fi
 	echo ""
 }
-TRAP_ON	# Active trap pour arrêter le script si une erreur est détectée.
+ynh_abort_if_errors	# Active trap pour arrêter le script si une erreur est détectée.
 
-# Retrieve arguments
+#=================================================
+# RETRIEVE ARGUMENTS FROM THE MANIFEST
+#=================================================
+
 domain=$YNH_APP_ARG_DOMAIN
 admin=$YNH_APP_ARG_ADMIN
 password=$YNH_APP_ARG_PASSWORD
 language=$YNH_APP_ARG_LANGUAGE
 is_public=$YNH_APP_ARG_IS_PUBLIC
 abiword=$YNH_APP_ARG_ABIWORD
-path="" # Assure la compatibilité avec les fonctions utilisant $path
+path_url="" # Assure la compatibilité avec les fonctions utilisant $path_url
 
 app=$YNH_APP_INSTANCE_NAME
 
-# Source app helpers
-source /usr/share/yunohost/helpers
-
-# Vérifie que les variables ne sont pas vides.
-CHECK_VAR "$app" "app name not set"
+#=================================================
+# CHECK IF THE APP CAN BE INSTALLED WITH THIS ARGS
+#=================================================
 
 CHECK_USER "$admin"	# Vérifie la validité de l'user admin
 
 if [ "${#password}" -lt 8 ] || [ "${#password}" -gt 30 ]
 then
-	echo "The password must be between 8 and 30 characters." >&2 && false
+	ynh_die "The password must be between 8 and 30 characters."
 fi
 
 if sudo yunohost domain list | grep -q $domain	# Vérifie la liste des domaines
 then	# Si le domaine existe dans Yunohost
 	if sudo yunohost app map | grep -q $domain	# Vérifie la liste des apps par domaine
 	then 	# Si une app est installée sur ce domaine.
-		echo "An app is already installed on the domain $domain. Mypads needs a whole domain or subdomain to himself." >&2
+		WARNING echo "An app is already installed on the domain $domain. Mypads needs a whole domain or subdomain to himself."
 	fi
 fi
 
 CHECK_DOMAINPATH	# Vérifie la disponibilité du path et du domaine.
-
 CHECK_FINALPATH	# Vérifie que le dossier de destination n'est pas déjà utilisé.
 
+#=================================================
+# STORE SETTINGS FROM MANIFEST
+#=================================================
 
-FIND_PORT 9001	# Cherche un port libre.
-
-# Enregistre les infos dans la config YunoHost
 ynh_app_setting_set $app domain $domain
 ynh_app_setting_set $app admin $admin
 ynh_app_setting_set $app is_public $is_public
 ynh_app_setting_set $app password $password
 ynh_app_setting_set $app language $language
-ynh_app_setting_set $app port $port
 ynh_app_setting_set $app abiword $abiword
 
+#=================================================
+# STANDARD MODIFICATIONS
+#=================================================
+# FIND AND OPEN A PORT
+#=================================================
 
-GENERATE_DB $app	# Créer une base de données et un utilisateur dédié au nom de l'app.
+port=$(ynh_find_port 9001)	# Cherche un port libre.
+ynh_app_setting_set $app port $port
 
+#=================================================
+# INSTALL DEPENDENCIES
+#=================================================
 
-# Créer le repertoire de destination et stocke son emplacement.
-sudo mkdir "$final_path"
+if [ $abiword -eq 1 ]
+then
+	ynh_install_app_dependencies npm nodejs-legacy abiword
+else
+	ynh_install_app_dependencies npm nodejs-legacy
+fi
+
+#=================================================
+# CREATE A SQL BDD
+#=================================================
+
+db_name=$(ynh_make_valid_dbid $app)
+ynh_app_setting_set $app db_name $db_name
+ynh_mysql_generate_db $db_name $db_name
+
+#=================================================
+# DOWNLOAD, CHECK AND UNPACK SOURCE
+#=================================================
+
 ynh_app_setting_set $app final_path $final_path
+SETUP_SOURCE	# Télécharge la source, décompresse et copie dans $final_path
 
-SETUP_SOURCE "1.6.0.tar.gz"	# Télécharge la source, décompresse et copie dans $final_path
+#=================================================
+# NGINX CONFIGURATION
+#=================================================
 
 # Et copie le fichier de config nginx
 sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
-
 # Modifie les variables dans le fichier de configuration nginx
 sudo sed -i "s@__PORT__@$port@g" /etc/nginx/conf.d/$domain.d/$app.conf
 
-# Installation de npm et nodejs
-sudo apt-get update
-sudo apt-get install npm nodejs-legacy -qy
+#=================================================
+# CREATE DEDICATED USER
+#=================================================
 
-ADD_SYS_USER	# Créer un user système dédié pour l'application
+ynh_system_user_create $app	# Créer un utilisateur système dédié à l'app
+
+#=================================================
+# SPECIFIC SETUP
+#=================================================
+# HANDLE LOG FILES AND LOGROTATE
+#=================================================
 
 # Créer le dossier de log
 sudo mkdir -p /var/log/$app
@@ -91,22 +135,30 @@ sudo touch $install_log
 sudo chown $app -R /var/log/$app
 sudo chown admin -R $install_log
 
+# Configuration de logrotate
+ynh_use_logrotate
+
+#=================================================
+# INSTALL ETHERPAD
+#=================================================
+
 # Installe les dépendances de etherpad et procède à l'intallation.
-# sudo bash -c "\"$final_path/bin/installDeps.sh\" > $install_log 2>&1"
 sudo "$final_path/bin/installDeps.sh" > $install_log 2>&1
 sudo npm install forever -g >> $install_log 2>&1
 
-# Configure etherpad
+#=================================================
+# CONFIGURE ETHERPAD
+#=================================================
+
 sudo cp ../conf/settings.json "$final_path/settings.json"
 sudo cp ../conf/credentials.json "$final_path/credentials.json"
 sudo sed -i "s/__PORT__/$port/g" "$final_path/settings.json"
-sudo sed -i "s/__DB_USER__/$db_user/g" "$final_path/credentials.json"
+sudo sed -i "s/__DB_USER__/$db_name/g" "$final_path/credentials.json"
 sudo sed -i "s/__DB_PWD__/$db_pwd/g" "$final_path/credentials.json"
 sudo sed -i "s/__ADMIN__/$admin/g" "$final_path/credentials.json"
 sudo sed -i "s/__PASSWD__/$password/g" "$final_path/credentials.json"
 if [ "$abiword" -eq 1 ]
 then
-	sudo apt-get install abiword -qy	# Installation de abiword
 	abiword_path=`which abiword`	# Récupère l'emplacement de l'exécutable de abiword
 	sudo sed -i "s@\"abiword\" : null@\"abiword\" : \"$abiword_path\"@" "$final_path/settings.json"	# Renseigne l'emplacement de abiword dans la config de etherpad
 fi
@@ -114,18 +166,19 @@ sudo sed -i "s/__LANGUAGE__/$language/g" "$final_path/settings.json"
 STORE_MD5_CONFIG "settings.json" "$final_path/settings.json"	# Enregistre la somme de contrôle du fichier de config
 STORE_MD5_CONFIG "credentials.json" "$final_path/credentials.json"	# Enregistre la somme de contrôle du fichier de config
 
-# Configure les droits d'accès au fichiers
+
+#=================================================
+# SECURING FILES AND DIRECTORIES
+#=================================================
+
 # Les fichiers appartiennent à etherpad
 sudo chown -R $app: $final_path
 sudo chmod 600 $final_path/credentials.json	# Restreint l'accès à credentials.json
 
+#=================================================
+# SETUP SYSTEMD
+#=================================================
 
-# Configuration de logrotate
-sed -i "s@__APP__@$app@g" ../conf/logrotate
-sudo cp ../conf/logrotate /etc/logrotate.d/$app
-
-
-# Mise en place du script systemd
 sudo cp ../conf/etherpad.service /etc/systemd/system/$app.service
 sudo chown root: /etc/systemd/system/$app.service
 sudo sed -i "s@__FINALPATH__@$final_path/@g" /etc/systemd/system/$app.service
@@ -133,11 +186,17 @@ sudo sed -i "s@__APP__@$app@g" /etc/systemd/system/$app.service
 ## Démarrage auto du service
 sudo systemctl enable $app
 
+#=================================================
+# ENABLE SERVICE IN ADMIN PANEL
+#=================================================
+
 # Ajoute le service au monitoring de Yunohost.
 sudo yunohost service add $app --log "/var/log/$app/etherpad.log"
 
+#=================================================
+# INSTALL FRAMAPAD'S PLUGINS
+#=================================================
 
-# Installation des plugins etherpad (Framapad style)
 script_dir="$PWD"
 cd "$final_path"
 sudo npm install ep_align >> $install_log 2>&1	# Add Left/Center/Right/Justify to lines of text in a pad
@@ -158,6 +217,10 @@ sudo npm install ep_table_of_contents >> $install_log 2>&1	# Framapad - View a t
 sudo npm install ep_user_font_size >> $install_log 2>&1	# Framapad - User Pad Contents font size can be set in settings, this does not effect other peoples views
 sudo chown -R $app: $final_path/node_modules
 
+#=================================================
+# SOME HACKS
+#=================================================
+
 # Ajoute un lien vers etherpad pour créer des pads anonymes depuis Mypads.
 sudo sed -i "s@^ *\"DESCRIPTION\": .*</ul>@&<a href=../>Pads anonymes</a>@g" $final_path/node_modules/ep_mypads/static/l10n/fr.json
 sudo sed -i "s@^ *\"DESCRIPTION\": .*</ul>@&<a href=../>Anonymous pads</a>@g" $final_path/node_modules/ep_mypads/static/l10n/en.json
@@ -167,46 +230,56 @@ sudo sed -i "s@^ *\"FOOTER\": .*2.0@& | <a href='../admin'>Etherpad admin</a>@g"
 mod_line=$(grep -nA5 "index.createOpenPad" $final_path/src/templates/index.html | grep "</div>" | cut -d '-' -f 1)	# Recherche le /div situé sous le champs d'ouverture de pad.
 sudo sed -i "$mod_line s@div>@&\n\t<center><br><font size="5"><a href="./mypads">Mypads</a></font></center>@" $final_path/src/templates/index.html	# Pour ajouter un lien vers le plugin mypads depuis la page d'Etherpad.
 
-# Démarre etherpad
-echo "Démarrage d'etherpad" >&2
+#=================================================
+# START ETHERPAD IN BACKGROUND
+#=================================================
+
+WARNING echo "Démarrage d'etherpad"
 tempfile="$(mktemp)"
 tail -f -n1 /var/log/$app/etherpad.log > "$tempfile" &	# Suit le démarrage dans le log
 PID_TAIL=$!	# Récupère le PID de la commande tail, qui est passée en arrière plan.
-sudo service $app start	# Démarre etherpad. Le démarrage est fait le plus tôt possible, car il est très long...
+sudo systemctl start $app	# Démarre etherpad. Le démarrage est fait le plus tôt possible, car il est très long...
 
-# Make app public if necessary
-if [ "$is_public" = "Yes" ]; then
+#=================================================
+# SETUP SSOWAT
+#=================================================
+
+if [ $is_public -eq 1 ]; then
 	ynh_app_setting_set $app skipped_uris "/"
 else
 	ynh_app_setting_set $app skipped_uris "/admin"	# La page d'admin etherpad ne supporte pas le sso...
 fi
 
-# Recharge la configuration Nginx
-sudo service nginx reload
-# Régénère la configuration de SSOwat
-sudo yunohost app ssowatconf
+#=================================================
+# RELOAD NGINX
+#=================================================
 
-# Surveille le démarrage du service.
+sudo systemctl reload nginx
+
+#=================================================
+# CHECK ETHERPAD STARTING
+#=================================================
+
 lang_OK=0
 for i in `seq 1 120`
 do	# La boucle attend le démarrage d'etherpad. Ou 2 minutes. Cette boucle évite simplement un 502 au début, car le démarrage est long...
 	if grep -q "You can access your Etherpad instance at" "$tempfile" && [ "$lang_OK" -eq 0 ] ; then
 		# Si le log annonce une première fois le démarrage d'etherpad, applique la langue de mypads et redémarre le service.
-		echo "Le service $app a démarré correctement." >&2
+		WARNING echo "Le service $app a démarré correctement."
 		sudo sed -i "s/__LANGUAGE__/$language/g" "$script_dir/../conf/lang_mypads.sql"
-		mysql -u $db_user -p$db_pwd $db_user < "$script_dir/../conf/lang_mypads.sql"
+		mysql -u $db_name -p$db_pwd $db_name < "$script_dir/../conf/lang_mypads.sql"
 		echo ""
-		sudo service $app restart
+		sudo systemctl restart $app
 		cat /dev/null > "$tempfile"	# Purge le log de suivi du démarrage.
 		lang_OK=1
 		i=1;
 	fi
 	if grep -q "You can access your Etherpad instance at" "$tempfile" && [ "$lang_OK" -eq 1 ]; then
-		echo "Le service $app a démarré correctement." >&2
+		WARNING echo "Le service $app a démarré correctement."
 		break	# Si le log annonce une deuxième fois le démarrage d'etherpad, sort de la boucle.
 	fi
-	echo -n "." >&2
+	WARNING echo -n "."
 	sleep 1
 done
-kill -s 15 $PID_TAIL > /dev/null	# Arrête l'exécution de tail.
+SUPPRESS_WARNING kill -s 15 $PID_TAIL	# Arrête l'exécution de tail.
 sudo rm "$tempfile"
diff --git a/scripts/restore b/scripts/restore
--- a/scripts/restore
+++ b/scripts/restore
@@ -1,40 +1,85 @@
 #!/bin/bash
 
-# Source app helpers
+#=================================================
+# GENERIC STARTING
+#=================================================
+# MANAGE FAILURE OF THE SCRIPT
+#=================================================
+
+# Exit on command errors and treat unset variables as an error
+set -eu
+
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
+
+if [ ! -e .fonctions ]; then
+	# Rapatrie le fichier de fonctions si il n'est pas dans le dossier courant
+	sudo cp ../settings/scripts/.fonctions ./.fonctions
+	sudo chmod a+rx .fonctions
+fi
+source .fonctions
 source /usr/share/yunohost/helpers
 
-# Récupère les infos de l'application.
+#=================================================
+# LOAD SETTINGS
+#=================================================
+
 app=$YNH_APP_INSTANCE_NAME
+
 domain=$(ynh_app_setting_get $app domain)
+path_url=$(ynh_app_setting_get $app path_url)
 final_path=$(ynh_app_setting_get $app final_path)
+db_name=$(ynh_app_setting_get $app db_name)
+abiword=$(ynh_app_setting_get $app abiword)
 
-if [ -d $final_path ]; then
-    ynh_die "There is already a directory: $final_path"
-fi
+#=================================================
+# CHECK IF THE APP CAN BE RESTORED
+#=================================================
 
-# The parameter $1 is the uncompressed restore directory location
-backup_dir=$1/apps/$app
+sudo yunohost app checkurl "${domain}${path_url}" -a "$app" \
+	|| ynh_die "Path not available: ${domain}${path_url}"
+test ! -d $final_path \
+	|| ynh_die "There is already a directory: $final_path "
 
-# Restore Nginx
+#=================================================
+# STANDARD RESTORE STEPS
+#=================================================
+# RESTORE OF THE NGINX CONFIGURATION
+#=================================================
+
 conf=/etc/nginx/conf.d/$domain.d/$app.conf
 if [ -f $conf ]; then
-    ynh_die "There is already a nginx conf file at this path: $conf"
+	ynh_die "There is already a nginx conf file at this path: $conf "
 fi
-sudo cp -a $backup_dir/nginx.conf $conf
+sudo cp -a ./nginx.conf $conf
 
-# Restore YunoHost parameters
-sudo cp -a $backup_dir/yunohost/. /etc/yunohost/apps/$app
+#=================================================
+# RESTORE OF THE MAIN DIR OF THE APP
+#=================================================
 
-# Restore sources & data
-sudo cp -a "$backup_dir/sources/." $final_path
+sudo cp -a ./sources/. $final_path
 
-# ADD_SYS_USER	# Créer un user système dédié pour l'application
-if ! ynh_system_user_exists "$app"	# Test l'existence de l'utilisateur
-then
-	sudo useradd -d /var/www/$app --system --user-group $app --shell /usr/sbin/nologin || (echo "Unable to create $app system account" >&2 && false)
-fi
+#=================================================
+# RESTORE OF THE SQL BDD
+#=================================================
 
-# Créer le dossier de log
+db_pwd=$(ynh_app_setting_get $app mysqlpwd)
+ynh_mysql_create_db $db_name $db_name $db_pwd
+ynh_mysql_connect_as $db_name $db_pwd $db_name < ./db.sql
+
+#=================================================
+# RECREATE OF THE DEDICATED USER
+#=================================================
+
+ynh_system_user_create $app	# Recreate the dedicated user, if not exist
+
+#=================================================
+# SPECIFIC RESTORE
+#=================================================
+# HANDLE LOG FILES AND LOGROTATE
+#=================================================
+
 sudo mkdir -p /var/log/$app
 sudo touch /var/log/$app/etherpad.log
 install_log=/var/log/$app/installation.log
@@ -42,40 +87,59 @@ sudo touch $install_log
 sudo chown $app -R /var/log/$app
 sudo chown admin -R $install_log
 
-# Installation de npm et nodejs
-sudo apt-get update
-sudo apt-get install npm nodejs-legacy -qy
+# Restaure la configuration de logrotate
+sudo cp -a ./logrotate /etc/logrotate.d/$app
 
-# Installe les dépendances de etherpad
-# sudo "$final_path/bin/installDeps.sh" > $install_log 2>&1
+#=================================================
+# INSTALL DEPENDENCIES
+#=================================================
+
+if [ "$abiword" -eq 1 ]
+then
+	ynh_install_app_dependencies npm nodejs-legacy abiword
+else
+	ynh_install_app_dependencies npm nodejs-legacy
+fi
+
+#=================================================
+# INSTALL ETHERPAD DEPENDENCIES
+#=================================================
+
 sudo npm install forever -g >> $install_log 2>&1
 
-# Créer la base de donnée et la restaure
-db_pwd=$(ynh_app_setting_get $app mysqlpwd)
-db_user=$app
-ynh_mysql_create_db $db_user $db_user $db_pwd
-mysql --debug-check -u $db_user -p$db_pwd $db_user < ${backup_dir}/db.sql
+#=================================================
+# ENABLE SERVICE IN ADMIN PANEL
+#=================================================
 
-# Restaure la configuration de logrotate
-sudo cp -a $backup_dir/logrotate /etc/logrotate.d/$app
-
-# Ajoute le service au monitoring de Yunohost.
 sudo yunohost service add $app --log "/var/log/$app/etherpad.log"
 
-# Restauration des fichiers du script systemd
-sudo cp -a $backup_dir/$app.service /etc/systemd/system/$app.service
+#=================================================
+# RESTORE SYSTEMD
+#=================================================
+
+sudo cp -a ./systemd /etc/systemd/system/$app.service
 ## Démarrage auto du service
 sudo systemctl enable $app.service
 
-# Démarre etherpad
+#=================================================
+# START ETHERPAD IN BACKGROUND
+#=================================================
+
 echo "Démarrage d'etherpad" >&2
 tempfile="$(mktemp)"
 tail -f -n1 /var/log/$app/etherpad.log > "$tempfile" &	# Suit le démarrage dans le log
 PID_TAIL=$!	# Récupère le PID de la commande tail, qui est passée en arrière plan.
-sudo service $app start	# Démarre etherpad. Le démarrage est fait le plus tôt possible, car il est très long...
+sudo systemctl start $app	# Démarre etherpad. Le démarrage est fait le plus tôt possible, car il est très long...
 
-# Reload webserver
-sudo service nginx reload
+#=================================================
+# RELOAD NGINX
+#=================================================
+
+sudo systemctl reload nginx
+
+#=================================================
+# CHECK ETHERPAD STARTING
+#=================================================
 
 # Surveille le démarrage du service.
 for i in `seq 1 60`
diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -1,31 +1,79 @@
 #!/bin/bash
 
-source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script
+#=================================================
+# GENERIC STARTING
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
 
-# Source app helpers
+source .fonctions
 source /usr/share/yunohost/helpers
 
-# Récupère les infos de l'application.
+#=================================================
+# LOAD SETTINGS
+#=================================================
+
 app=$YNH_APP_INSTANCE_NAME
+
 domain=$(ynh_app_setting_get $app domain)
-path=$(ynh_app_setting_get $app path)
 admin=$(ynh_app_setting_get $app admin)
 language=$(ynh_app_setting_get $app language)
 is_public=$(ynh_app_setting_get $app is_public)
 final_path=$(ynh_app_setting_get $app final_path)
 port=$(ynh_app_setting_get $app port)
 abiword=$(ynh_app_setting_get $app abiword)
+db_name=$(ynh_app_setting_get $app db_name)
 
-SETUP_SOURCE "1.6.0.tar.gz"	# Télécharge la source, décompresse et copie dans $final_path
+#=================================================
+# FIX OLD THINGS
+#=================================================
 
-# Et copie le fichier de config nginx
+if [ "$is_public" = "Yes" ]; then
+	ynh_app_setting_set $app is_public 1	# Fixe is_public en booléen
+	is_public=1
+elif [ "$is_public" = "No" ]; then
+	ynh_app_setting_set $app is_public 0
+	is_public=0
+fi
+
+if [ -z $db_name ]; then	# Si db_name n'est pas renseigné dans app setting
+	db_name=$(ynh_make_valid_dbid $app)
+	ynh_app_setting_set $app db_name $db_name
+fi
+
+#=================================================
+# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
+#=================================================
+
+BACKUP_BEFORE_UPGRADE	# Backup the current version of the app
+ynh_clean_setup () {
+	BACKUP_FAIL_UPGRADE	# restore it if the upgrade fails
+}
+ynh_abort_if_errors	# Active trap pour arrêter le script si une erreur est détectée.
+
+#=================================================
+# STANDARD UPGRADE STEPS
+#=================================================
+# DOWNLOAD, CHECK AND UNPACK SOURCE
+#=================================================
+
+SETUP_SOURCE	# Télécharge la source, décompresse et copie dans $final_path
+
+#=================================================
+# NGINX CONFIGURATION
+#=================================================
+
+# Copie le fichier de config nginx
 sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
-
 # Modifie les variables dans le fichier de configuration nginx
 sudo sed -i "s@__PORT__@$port@g" /etc/nginx/conf.d/$domain.d/$app.conf
 
+#=================================================
+# SPECIFIC UPGRADE
+#=================================================
+# CONFIGURE ETHERPAD
+#=================================================
 
-# Configure etherpad
 # Copie ou modification d'un fichier de config
 CHECK_MD5_CONFIG "settings.json" "$final_path/settings.json"	# Créé un backup du fichier de config si il a été modifié.
 CHECK_MD5_CONFIG "credentials.json" "$final_path/credentials.json"	# Créé un backup du fichier de config si il a été modifié.
@@ -34,6 +82,7 @@ sudo cp ../conf/credentials.json "$final_path/credentials.json"
 sudo sed -i "s/__PORT__/$port/g" "$final_path/settings.json"
 sudo sed -i "s/__DB_USER__/$app/g" "$final_path/credentials.json"
 db_pwd=$(ynh_app_setting_get $app mysqlpwd)
+password=$(ynh_app_setting_get $app password)
 sudo sed -i "s/__DB_PWD__/$db_pwd/g" "$final_path/credentials.json"
 sudo sed -i "s/__ADMIN__/$admin/g" "$final_path/credentials.json"
 sudo sed -i "s/__PASSWD__/$password/g" "$final_path/credentials.json"
@@ -43,28 +92,40 @@ then
 	sudo sed -i "s@\"abiword\" : null@\"abiword\" : \"$abiword_path\"@" "$final_path/settings.json"	# Renseigne l'emplacement de abiword dans la config de etherpad
 fi
 if test -z $language; then
-    language=en # En cas d'upgrade d'une version ne gérant pas la langue, la langue est anglais par défaut
-    ynh_app_setting_set $app language $language
+	language=en # En cas d'upgrade d'une version ne gérant pas la langue, la langue est anglais par défaut
+	ynh_app_setting_set $app language $language
 fi
 sudo sed -i "s/__LANGUAGE__/$language/g" "$final_path/settings.json"
 STORE_MD5_CONFIG "settings.json" "$final_path/settings.json"	# Réenregistre la somme de contrôle du fichier de config
 STORE_MD5_CONFIG "credentials.json" "$final_path/credentials.json"	# Réenregistre la somme de contrôle du fichier de config
 
-# Configure les droits d'accès au fichiers
+#=================================================
+# CREATE DEDICATED USER
+#=================================================
+
+ynh_system_user_create $app	# Create the dedicated user, if not exist
+
+#=================================================
+# SECURING FILES AND DIRECTORIES
+#=================================================
+
 # Les fichiers appartiennent à etherpad
-ADD_SYS_USER	# Créer un user système dédié pour l'application
 sudo chown -R $app: $final_path
 sudo chmod 600 "$final_path/credentials.json"	# Restreint l'accès à credentials.json
 sudo chown $app -R /var/log/$app/etherpad.log
 
+#=================================================
+# SETUP LOGROTATE
+#=================================================
 
-# Configuration de logrotate
-sed -i "s@__APP__@$app@g" ../conf/logrotate
-sudo cp ../conf/logrotate /etc/logrotate.d/$app
+ynh_use_logrotate
 
+#=================================================
+# SETUP SYSTEMD
+#=================================================
 
 # Mise en place du script systemd
-sudo service $app stop
+sudo systemctl stop $app
 sudo cp ../conf/etherpad.service /etc/systemd/system/$app.service
 sudo chown root: /etc/systemd/system/$app.service
 sudo sed -i "s@__FINALPATH__@$final_path/@g" /etc/systemd/system/$app.service
@@ -72,48 +133,54 @@ sudo sed -i "s@__APP__@$app@g" /etc/systemd/system/$app.service
 ## Démarrage auto du service
 sudo systemctl enable $app
 
-# Ajoute un lien vers etherpad pour créer des pads anonymes depuis Mypads.
-# sudo sed -i "s@^ *\"DESCRIPTION\": .*</ul>@&<a href=../>Pads anonymes</a>@g" $final_path/node_modules/ep_mypads/static/l10n/fr.json
-# sudo sed -i "s@^ *\"DESCRIPTION\": .*</ul>@&<a href=../>Anonymous pads</a>@g" $final_path/node_modules/ep_mypads/static/l10n/en.json
-# Et un lien vers l'admin etherpad depuis Mypads.
-# sudo sed -i "s@^ *\"FOOTER\": .*2.0@& | <a href='../admin'>Etherpad admin</a>@g" $final_path/node_modules/ep_mypads/static/l10n/en.json $final_path/node_modules/ep_mypads/static/l10n/fr.json
+#=================================================
+# SOME HACKS
+#=================================================
 
 mod_line=$(grep -nA5 "index.createOpenPad" $final_path/src/templates/index.html | grep "</div>" | cut -d '-' -f 1)	# Recherche le /div situé sous le champs d'ouverture de pad.
 sudo sed -i "$mod_line s@div>@&\n\t<center><br><font size="5"><a href="./mypads">Mypads</a></font></center>@" $final_path/src/templates/index.html	# Pour ajouter un lien vers le plugin mypads depuis la page d'Etherpad.
 
-# sudo mkdir -p /home/.etherpad
-# sudo chown $app: -R /home/.etherpad
-# sudo usermod -d /home/.etherpad $app
+#=================================================
+# START ETHERPAD IN BACKGROUND
+#=================================================
 
 # Démarre etherpad
-echo "Démarrage d'etherpad" >&2
+WARNING echo "Démarrage d'etherpad"
 tempfile="$(mktemp)"
 tail -f -n1 /var/log/$app/etherpad.log > "$tempfile" &	# Suit le démarrage dans le log
 PID_TAIL=$!	# Récupère le PID de la commande tail, qui est passée en arrière plan.
-sudo service $app start	# Démarre etherpad. Le démarrage est fait le plus tôt possible, car il est très long...
+sudo systemctl start $app	# Démarre etherpad. Le démarrage est fait le plus tôt possible, car il est très long...
+
+#=================================================
+# SETUP SSOWAT
+#=================================================
 
 # Make app public if necessary
-if [ "$is_public" = "Yes" ]; then
+if [ $is_public -eq 1 ]; then
 	ynh_app_setting_set $app skipped_uris "/"
 else
 	ynh_app_setting_set $app skipped_uris "/admin"	# La page d'admin etherpad ne supporte pas le sso...
 fi
 
-# Recharge la configuration Nginx
-sudo service nginx reload
-# Régénère la configuration de SSOwat
-sudo yunohost app ssowatconf
+#=================================================
+# RELOAD NGINX
+#=================================================
 
-# Surveille le démarrage du service.
+sudo systemctl reload nginx
+
+#=================================================
+# CHECK ETHERPAD STARTING
+#=================================================
+
 for i in `seq 1 60`
 do	# La boucle attend le démarrage d'etherpad. Ou 1 minute. Cette boucle évite simplement un 502 au début, car le démarrage est long...
 	if grep -q "You can access your Etherpad instance at" "$tempfile"; then
-		echo "Le service $app a démarré correctement." >&2
+		WARNING echo "Le service $app a démarré correctement."
 		break	# Si le log annonce le démarrage d'etherpad, sort de la boucle.
 	fi
-	echo -n "." >&2
+	WARNING echo -n "."
 	sleep 1
 done
 echo ""
-kill -s 15 $PID_TAIL > /dev/null	# Arrête l'exécution de tail.
+QUIET kill -s 15 $PID_TAIL	# Arrête l'exécution de tail.
 sudo rm "$tempfile"
