Apply last example_ynh

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #=================================================
-# GENERIC STARTING
+# GENERIC START
 #=================================================
 # IMPORT GENERIC HELPERS
 #=================================================
@@ -21,8 +21,8 @@ app=$YNH_APP_INSTANCE_NAME
 domain=$(ynh_app_setting_get --app=$app --key=domain)
 path_url=$(ynh_app_setting_get --app=$app --key=path)
 admin=$(ynh_app_setting_get --app=$app --key=admin)
-language=$(ynh_app_setting_get --app=$app --key=language)
 final_path=$(ynh_app_setting_get --app=$app --key=final_path)
+language=$(ynh_app_setting_get --app=$app --key=language)
 port=$(ynh_app_setting_get --app=$app --key=port)
 export=$(ynh_app_setting_get --app=$app --key=export)
 db_name=$(ynh_app_setting_get --app=$app --key=db_name)
@@ -46,11 +46,42 @@ pad_config_show_markdown=$(ynh_app_setting_get --app=$app --key=pad_config_show_
 #=================================================
 # CHECK VERSION
 #=================================================
-
-# Wait for etherpad to be fully started
-ynh_systemd_action --action=restart --line_match="You can access your Etherpad instance at" --log_path="/var/log/$app/etherpad.log" --timeout="120"
+ynh_script_progression --message="Checking version..."
 
 upgrade_type=$(ynh_check_app_version_changed)
+
+#=================================================
+# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
+#=================================================
+ynh_script_progression --message="Backing up the app before upgrading (may take a while)..." --weight=35
+
+# Backup the current version of the app
+ynh_backup_before_upgrade
+ynh_clean_setup () {
+	# Clean installation remainings that are not handled by the remove script.
+	ynh_clean_check_starting
+
+	# Restore it if the upgrade fails
+	ynh_restore_upgradebackup
+}
+# Exit if an error occurs during the execution of the script
+ynh_abort_if_errors
+
+#=================================================
+# ACTIVATE MAINTENANCE MODE
+#=================================================
+ynh_script_progression --message="Activating maintenance mode..." --weight=2
+
+ynh_maintenance_mode_ON
+
+#=================================================
+# STANDARD UPGRADE STEPS
+#=================================================
+# STOP SYSTEMD SERVICE
+#=================================================
+ynh_script_progression --message="Stopping a systemd service..." --weight=3
+
+ynh_systemd_action --service_name=$app --action=stop
 
 #=================================================
 # ENSURE DOWNWARD COMPATIBILITY
@@ -128,46 +159,15 @@ fi
 
 # Cleaning legacy permissions
 if ynh_legacy_permissions_exists; then
-  ynh_legacy_permissions_delete_all
+	ynh_legacy_permissions_delete_all
 
-  ynh_app_setting_delete --app=$app --key=is_public
+	ynh_app_setting_delete --app=$app --key=is_public
 fi
 
 if ! ynh_permission_exists --permission="admin"; then
-  # Create the required permissions
-  ynh_permission_create --permission="admin" --url="/admin" --allowed=$admin
+	# Create the required permissions
+	ynh_permission_create --permission="admin" --url="/admin" --allowed=$admin
 fi
-
-#=================================================
-# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
-#=================================================
-ynh_script_progression --message="Backing up the app before upgrading (may take a while)..." --weight=35
-
-# Backup the current version of the app
-ynh_backup_before_upgrade
-ynh_clean_setup () {
-# Clean installation remainings that are not handled by the remove script.
-	ynh_clean_check_starting
-
-	# Restore it if the upgrade fails
-	ynh_restore_upgradebackup
-}
-# Exit if an error occurs during the execution of the script
-ynh_abort_if_errors
-
-#=================================================
-# ACTIVATE MAINTENANCE MODE
-#=================================================
-ynh_script_progression --message="Activating maintenance mode..." --weight=2
-
-ynh_maintenance_mode_ON
-
-#=================================================
-# STOP ETHERPAD
-#=================================================
-ynh_script_progression --message="Stopping Etherpad service..." --weight=3
-
-ynh_systemd_action --action=stop
 
 #=================================================
 # CREATE DEDICATED USER
@@ -178,8 +178,6 @@ ynh_script_progression --message="Making sure dedicated system user exists..."
 ynh_system_user_create --username=$app --home_dir=$final_path
 
 #=================================================
-# STANDARD UPGRADE STEPS
-#=================================================
 # DOWNLOAD, CHECK AND UNPACK SOURCE
 #=================================================
 
@@ -187,22 +185,37 @@ if [ "$upgrade_type" == "UPGRADE_APP" ]
 then
 	ynh_script_progression --message="Upgrading source files..." --weight=4
 
-  # # Create a temporary directory
-  # tmpdir="$(mktemp -d)"
-  # # Backup the config file in the temp dir
-  # cp -a "$final_path/settings.json" "$tmpdir/settings.json"
+	# Create a temporary directory
+  	tmpdir="$(mktemp -d)"
+	# Backup the config file in the temp dir
+	cp -a "$final_path/settings.json" "$tmpdir/settings.json"
 
-  ynh_secure_remove --file="$final_path"
+	ynh_secure_remove --file="$final_path"
 
 	# Download, check integrity, uncompress and patch the source from app.src
 	ynh_setup_source --dest_dir="$final_path"
 
-  #   # Copy the admin saved settings from tmp directory to final config path 
-  # cp -a "$tmpdir/settings.json" "$final_path/settings.json" 
+  	# Copy the admin saved settings from tmp directory to final config path 
+	cp -a "$tmpdir/settings.json" "$final_path/settings.json" 
 
-  # # Remove the tmp directory securely
-  # ynh_secure_remove --file="$tmpdir"
+	# Remove the tmp directory securely
+	ynh_secure_remove --file="$tmpdir"
 
+fi
+
+chmod 750 "$final_path"
+chmod -R o-rwx "$final_path"
+chown -R $app:$app "$final_path"
+
+#=================================================
+# NGINX CONFIGURATION
+#=================================================
+ynh_script_progression --message="Upgrading NGINX web server configuration..."
+
+# Overwrite the NGINX configuration only if it's allowed
+if [ $overwrite_nginx -eq 1 ]
+then
+	ynh_add_nginx_config
 fi
 
 #=================================================
@@ -217,23 +230,14 @@ elif [ "$export" = "libreoffice" ]; then
 fi
 
 #=================================================
-# NGINX CONFIGURATION
-#=================================================
-ynh_script_progression --message="Upgrading NGINX web server configuration..."
-
-# Overwrite the NGINX configuration only if it's allowed
-if [ $overwrite_nginx -eq 1 ]
-then
-	ynh_add_nginx_config
-fi
-
-#=================================================
 # UPGRADE NODEJS
 #=================================================
 ynh_script_progression --message="Upgrading NodeJS..." --weight=4
 
 ynh_install_nodejs --nodejs_version=$nodejs_version
 
+#=================================================
+# SPECIFIC UPGRADE
 #=================================================
 # HANDLE LOG FILES AND LOGROTATE
 #=================================================
@@ -255,8 +259,8 @@ chown -R $app: $final_path
 pushd $final_path
   ynh_use_nodejs
   ynh_exec_as $app env "$ynh_node_load_PATH" src/bin/installDeps.sh
-# ynh_exec_warn_less npm cache clean --force
-# ynh_exec_warn_less ynh_exec_as $app env "$ynh_node_load_PATH" npm cache clean --force
+# ynh_exec_warn_less ynh_npm cache clean --force
+# ynh_exec_warn_less ynh_exec_as $app env "$ynh_node_load_PATH" ynh_npm cache clean --force
 # while read node_module
 # do
 #     # Ignore ep_etherpad-lite, this part is updated before in this script.
@@ -274,7 +278,7 @@ pushd $final_path
 #     if [ -n "${module_version}" ]; then
 #         module_version=@${module_version}
 #     fi
-#     ynh_exec_warn_less ynh_exec_as $app env "$ynh_node_load_PATH" npm install --upgrade ${node_module}${module_version} || true
+#     ynh_exec_warn_less ynh_exec_as $app env "$ynh_node_load_PATH" yh_npm install --upgrade ${node_module}${module_version} || true
 # done <<< "$(ls -1 "$final_path/node_modules" | grep "^ep_")"
 popd
 
@@ -316,7 +320,22 @@ popd
 chown -R $app: $final_path/node_modules
 
 #=================================================
-# SPECIFIC UPGRADE
+# SOME HACKS
+#=================================================
+
+if [ $mypads -eq 1 ]
+then
+	# Add a link to Etherpad to allow anonymous pads creation from MyPads.
+	ynh_replace_string --match_string="^ *\"DESCRIPTION\": .*</ul>" --replace_string="&<a href=../>Pads anonymes</a>" --target_file=$final_path/node_modules/ep_mypads/static/l10n/fr.json
+	ynh_replace_string --match_string="^ *\"DESCRIPTION\": .*</ul>" --replace_string="&<a href=../>Anonymous pads</a>" --target_file=$final_path/node_modules/ep_mypads/static/l10n/en.json
+	# And a link to etherpad admin from Mypads.
+	ynh_replace_string --match_string="^ *\"FOOTER\": .*2.0" --replace_string="& | <a href='../admin'>Etherpad admin</a>" --target_file=$final_path/node_modules/ep_mypads/static/l10n/en.json
+	ynh_replace_string --match_string="^ *\"FOOTER\": .*2.0" --replace_string="& | <a href='../admin'>Etherpad admin</a>" --target_file=$final_path/node_modules/ep_mypads/static/l10n/fr.json
+
+	# Find the /div just after the field to open a pad in order to add a link to MyPads plugin.
+	sed -i '157i<center><br><font size="4"><a href="./mypads/" style="text-decoration: none; color: #555">MyPads</a></font></center>' $final_path/src/templates/index.html
+fi
+
 #=================================================
 # CONFIGURE ETHERPAD
 #=================================================
@@ -400,10 +419,40 @@ chmod 600 "$final_path/credentials.json"
 chown $app -R /var/log/$app/etherpad.log
 
 #=================================================
-# ADVERTISE SERVICE IN ADMIN PANEL
+# SETUP SYSTEMD
 #=================================================
+ynh_script_progression --message="Upgrading systemd configuration..." --weight=2
+
+# Overwrite the systemd configuration only if it's allowed
+if [ $overwrite_systemd -eq 1 ]
+then
+	ynh_add_systemd_config
+fi
+
+#=================================================
+# GENERIC FINALIZATION
+#=================================================
+# SETUP LOGROTATE
+#=================================================
+ynh_script_progression --message="Upgrading logrotate configuration..."
+
+# Use logrotate to manage app-specific logfile(s)
+ynh_use_logrotate --non-append --specific_user=$app/$app
+
+#=================================================
+# INTEGRATE SERVICE IN YUNOHOST
+#=================================================
+ynh_script_progression --message="Integrating service in YunoHost..."
 
 yunohost service add $app --description="Collaborative editor" --log="/var/log/$app/etherpad.log"
+
+#=================================================
+# START SYSTEMD SERVICE
+#=================================================
+ynh_script_progression --message="Starting a systemd service..." --weight=9
+
+# Wait for etherpad to be fully started
+ynh_systemd_action --service_name=$app --action=restart --log_path="/var/log/$app/etherpad.log" --line_match="You can access your Etherpad instance at" --timeout="120"
 
 #=================================================
 # UPGRADE FAIL2BAN
@@ -414,48 +463,11 @@ ynh_script_progression --message="Reconfiguring Fail2Ban..." --weight=8
 ynh_add_fail2ban_config --logpath="/var/log/nginx/$domain-access.log" --failregex="<HOST> .* .POST /mypads/api/auth/login HTTP/1.1. 400" --max_retry=5
 
 #=================================================
-# SETUP LOGROTATE
-#=================================================
-ynh_script_progression --message="Upgrading logrotate configuration..."
-
-# Use logrotate to manage app-specific logfile(s)
-ynh_use_logrotate --non-append --specific_user=$app/$app
-
-#=================================================
-# SETUP SYSTEMD
-#=================================================
-ynh_script_progression --message="Upgrading systemd configuration..." --weight=2
-
-# Overwrite the systemd configuration only if it's allowed
-if [ $overwrite_systemd -eq 1 ]
-then
-	ynh_add_systemd_config --others_var="ynh_node_load_PATH"
-fi
-
-#=================================================
-# SOME HACKS
-#=================================================
-
-if [ "$upgrade_type" == "UPGRADE_APP" ] && [ $mypads -eq 1 ]
-then
-	# Find the /div just after the field to open a pad in order to add a link to mypads plugin.
-  sed -i '157i<center><br><font size="4"><a href="./mypads/" style="text-decoration: none; color: #555">MyPads</a></font></center>' $final_path/src/templates/index.html
-fi
-
-#=================================================
 # RELOAD NGINX
 #=================================================
 ynh_script_progression --message="Reloading NGINX web server..."
 
-ynh_systemd_action --action=reload --service_name=nginx
-
-#=================================================
-# CHECK ETHERPAD STARTING
-#=================================================
-ynh_script_progression --message="Restarting Etherpad..." --weight=9
-
-# Wait for etherpad to be fully started
-ynh_systemd_action --action=restart --line_match="You can access your Etherpad instance at" --log_path="/var/log/$app/etherpad.log" --timeout="120"
+ynh_systemd_action --service_name=nginx --action=reload
 
 #=================================================
 # DEACTIVE MAINTENANCE MODE
